version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts   ## 2.235.2    
    hostname: jenkins
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - .\\jenkins:/var/jenkins_home
  ssh:
    build: ssh\\.
    image: ssh_image
    hostname: ssh_container
    privileged: true
    user: root
    ports:
      - "2222:22"    
    container_name: ssh_container